package com.skipissue.maxway.domain.entity.responses

data class Order(
    val apartment: String,
    val building: String,
    val client_id: String,
    val client_name: String,
    val client_phone_number: String,
    val co_delivery_price: Int,
    val courier: Courier,
    val courier_id: String,
    val created_at: String,
    val delivery_price: Int,
    val delivery_time: String,
    val delivery_type: String,
    val description: String,
    val external_order_id: String,
    val extra_phone_number: String,
    val finished_at: String,
    val floor: String,
    val id: String,
    val is_courier_call: Boolean,
    val order_amount: Int,
    val paid: Boolean,
    val payment_type: String,
    val pos_id: String,
    val rating: String,
    val review: String,
    val source: String,
    val status_id: String,
    val status_notes: List<StatusNote>,
    val steps: List<Step>,
    val to_address: String,
    val to_location: ToLocation
)